### ISSUE TITLE
transcoding with ffmpeg.js (wasm)

### ISSUE THREAD

**Issue by mpisat** [apivideo/browserLiveStream#9]
Is it possible to use ffmpeg.js on the frontend side and transcode, then send pre-processed video to FFmpeg for relay (-c copy) for the final destination?

This way it won't consume much server resources and also paves the way for sending video directly from a web browser via websockify (it's just an idea) or node app (similar approach)

**Comment by dougsillars** [comment]
no it is not - you cannot open a RTMP socket from the browser (yet...)
